<?php

/**
 * PoliticalRegion seed data — self-referencing hierarchy.
 *
 * Top-level entries (parentSlug = null) are continent/macro-region groupings.
 * Child entries (parentSlug set) are sub-regions grouped by regulatory/business similarity.
 *
 * Countries reference a PoliticalRegion via `politicalRegionSlug` in their own config.
 *
 * Short codes: top-level uses 2-letter (EU, AM, AS, AF, OC, ME),
 * children use {parent}-{sub} pattern (EU-EU, AM-NA).
 * Numeric codes follow UN M49 where applicable.
 *
 * @see \DDD\Domain\Common\Entities\PoliticalEntities\PoliticalRegions\PoliticalRegion
 */
return [
    'politicalRegions' => [
        // ── Top-level regions (continents) ──────────────────────────
        'europe' => [
            'slug' => 'europe',
            'shortCode' => 'EU',
            'numericCode' => '150',
            'parentSlug' => null,
            'name' => [
                'en' => 'Europe',
                'de' => 'Europa',
                'fr' => 'Europe',
                'es' => 'Europa',
                'it' => 'Europa',
                'pt' => 'Europa',
                'nl' => 'Europa',
                'pl' => 'Europa',
                'ro' => 'Europa',
                'tr' => 'Avrupa',
                'ja' => 'ヨーロッパ',
                'zh' => '欧洲',
                'ar' => 'أوروبا',
                'uk' => 'Європа',
            ],
            'displayOrder' => 100,
            'isActive' => true,
        ],
        'americas' => [
            'slug' => 'americas',
            'shortCode' => 'AM',
            'numericCode' => '019',
            'parentSlug' => null,
            'name' => [
                'en' => 'Americas',
                'de' => 'Amerika',
                'fr' => 'Amériques',
                'es' => 'Américas',
                'it' => 'Americhe',
                'pt' => 'Américas',
                'nl' => 'Amerika',
                'pl' => 'Ameryki',
                'ro' => 'Americi',
                'tr' => 'Amerikalar',
                'ja' => 'アメリカ大陸',
                'zh' => '美洲',
                'ar' => 'الأمريكتان',
                'uk' => 'Америка',
            ],
            'displayOrder' => 200,
            'isActive' => true,
        ],
        'asia' => [
            'slug' => 'asia',
            'shortCode' => 'AS',
            'numericCode' => '142',
            'parentSlug' => null,
            'name' => [
                'en' => 'Asia',
                'de' => 'Asien',
                'fr' => 'Asie',
                'es' => 'Asia',
                'it' => 'Asia',
                'pt' => 'Ásia',
                'nl' => 'Azië',
                'pl' => 'Azja',
                'ro' => 'Asia',
                'tr' => 'Asya',
                'ja' => 'アジア',
                'zh' => '亚洲',
                'ar' => 'آسيا',
                'uk' => 'Азія',
            ],
            'displayOrder' => 300,
            'isActive' => true,
        ],
        'africa' => [
            'slug' => 'africa',
            'shortCode' => 'AF',
            'numericCode' => '002',
            'parentSlug' => null,
            'name' => [
                'en' => 'Africa',
                'de' => 'Afrika',
                'fr' => 'Afrique',
                'es' => 'África',
                'it' => 'Africa',
                'pt' => 'África',
                'nl' => 'Afrika',
                'pl' => 'Afryka',
                'ro' => 'Africa',
                'tr' => 'Afrika',
                'ja' => 'アフリカ',
                'zh' => '非洲',
                'ar' => 'أفريقيا',
                'uk' => 'Африка',
            ],
            'displayOrder' => 400,
            'isActive' => true,
        ],
        'oceania' => [
            'slug' => 'oceania',
            'shortCode' => 'OC',
            'numericCode' => '009',
            'parentSlug' => null,
            'name' => [
                'en' => 'Oceania',
                'de' => 'Ozeanien',
                'fr' => 'Océanie',
                'es' => 'Oceanía',
                'it' => 'Oceania',
                'pt' => 'Oceania',
                'nl' => 'Oceanië',
                'pl' => 'Oceania',
                'ro' => 'Oceania',
                'tr' => 'Okyanusya',
                'ja' => 'オセアニア',
                'zh' => '大洋洲',
                'ar' => 'أوقيانوسيا',
                'uk' => 'Океанія',
            ],
            'displayOrder' => 500,
            'isActive' => true,
        ],
        'mena' => [
            'slug' => 'mena',
            'shortCode' => 'ME',
            'numericCode' => null,
            'parentSlug' => null,
            'name' => [
                'en' => 'Middle East & North Africa',
                'de' => 'Naher Osten & Nordafrika',
                'fr' => 'Moyen-Orient & Afrique du Nord',
                'es' => 'Oriente Medio y Norte de África',
                'it' => 'Medio Oriente e Nord Africa',
                'pt' => 'Médio Oriente e Norte de África',
                'nl' => 'Midden-Oosten & Noord-Afrika',
                'pl' => 'Bliski Wschód i Afryka Północna',
                'ro' => 'Orientul Mijlociu și Africa de Nord',
                'tr' => 'Orta Doğu ve Kuzey Afrika',
                'ja' => '中東・北アフリカ',
                'zh' => '中东和北非',
                'ar' => 'الشرق الأوسط وشمال أفريقيا',
                'uk' => 'Близький Схід та Північна Африка',
            ],
            'displayOrder' => 600,
            'isActive' => true,
        ],

        // ── Europe — sub-regions ────────────────────────────────────
        'european-union' => [
            'slug' => 'european-union',
            'shortCode' => 'EU-EU',
            'numericCode' => null,
            'parentSlug' => 'europe',
            'name' => [
                'en' => 'European Union',
                'de' => 'Europäische Union',
                'fr' => 'Union européenne',
                'es' => 'Unión Europea',
                'it' => 'Unione Europea',
                'pt' => 'União Europeia',
                'nl' => 'Europese Unie',
                'pl' => 'Unia Europejska',
                'ro' => 'Uniunea Europeană',
            ],
            'displayOrder' => 100,
            'isActive' => true,
        ],
        'europe-non-eu' => [
            'slug' => 'europe-non-eu',
            'shortCode' => 'EU-XU',
            'numericCode' => null,
            'parentSlug' => 'europe',
            'name' => [
                'en' => 'EEA, EFTA & Non-EU Europe',
                'de' => 'EWR, EFTA & Nicht-EU-Europa',
                'fr' => 'EEE, AELE & Europe hors UE',
                'es' => 'EEE, AELC y Europa no UE',
            ],
            'displayOrder' => 200,
            'isActive' => true,
        ],
        'europe-east-balkans' => [
            'slug' => 'europe-east-balkans',
            'shortCode' => 'EU-EB',
            'numericCode' => '151',
            'parentSlug' => 'europe',
            'name' => [
                'en' => 'Eastern Europe & Balkans',
                'de' => 'Osteuropa & Balkan',
                'fr' => 'Europe de l\'Est & Balkans',
                'es' => 'Europa del Este y los Balcanes',
                'uk' => 'Східна Європа та Балкани',
            ],
            'displayOrder' => 300,
            'isActive' => true,
        ],

        // ── Americas — sub-regions ──────────────────────────────────
        'north-america' => [
            'slug' => 'north-america',
            'shortCode' => 'AM-NA',
            'numericCode' => '021',
            'parentSlug' => 'americas',
            'name' => [
                'en' => 'North America',
                'de' => 'Nordamerika',
                'fr' => 'Amérique du Nord',
                'es' => 'América del Norte',
                'pt' => 'América do Norte',
            ],
            'displayOrder' => 100,
            'isActive' => true,
        ],
        'central-america-caribbean' => [
            'slug' => 'central-america-caribbean',
            'shortCode' => 'AM-CA',
            'numericCode' => null,
            'parentSlug' => 'americas',
            'name' => [
                'en' => 'Central America & Caribbean',
                'de' => 'Zentralamerika & Karibik',
                'fr' => 'Amérique centrale & Caraïbes',
                'es' => 'Centroamérica y el Caribe',
                'pt' => 'América Central e Caribe',
            ],
            'displayOrder' => 200,
            'isActive' => true,
        ],
        'south-america' => [
            'slug' => 'south-america',
            'shortCode' => 'AM-SA',
            'numericCode' => '005',
            'parentSlug' => 'americas',
            'name' => [
                'en' => 'South America',
                'de' => 'Südamerika',
                'fr' => 'Amérique du Sud',
                'es' => 'América del Sur',
                'pt' => 'América do Sul',
            ],
            'displayOrder' => 300,
            'isActive' => true,
        ],

        // ── Asia — sub-regions ──────────────────────────────────────
        'east-southeast-asia' => [
            'slug' => 'east-southeast-asia',
            'shortCode' => 'AS-EA',
            'numericCode' => null,
            'parentSlug' => 'asia',
            'name' => [
                'en' => 'East & Southeast Asia',
                'de' => 'Ost- & Südostasien',
                'fr' => 'Asie de l\'Est & du Sud-Est',
                'es' => 'Asia Oriental y Sudoriental',
                'ja' => '東アジア・東南アジア',
                'zh' => '东亚和东南亚',
            ],
            'displayOrder' => 100,
            'isActive' => true,
        ],
        'south-asia' => [
            'slug' => 'south-asia',
            'shortCode' => 'AS-SA',
            'numericCode' => '034',
            'parentSlug' => 'asia',
            'name' => [
                'en' => 'South Asia',
                'de' => 'Südasien',
                'fr' => 'Asie du Sud',
                'es' => 'Asia Meridional',
                'hi' => 'दक्षिण एशिया',
            ],
            'displayOrder' => 200,
            'isActive' => true,
        ],
        'central-asia-caucasus' => [
            'slug' => 'central-asia-caucasus',
            'shortCode' => 'AS-CC',
            'numericCode' => '143',
            'parentSlug' => 'asia',
            'name' => [
                'en' => 'Central Asia & Caucasus',
                'de' => 'Zentralasien & Kaukasus',
                'fr' => 'Asie centrale & Caucase',
                'es' => 'Asia Central y Cáucaso',
                'ru' => 'Центральная Азия и Кавказ',
            ],
            'displayOrder' => 300,
            'isActive' => true,
        ],

        // ── Africa — sub-regions ────────────────────────────────────
        'sub-saharan-africa' => [
            'slug' => 'sub-saharan-africa',
            'shortCode' => 'AF-SS',
            'numericCode' => '202',
            'parentSlug' => 'africa',
            'name' => [
                'en' => 'Sub-Saharan Africa',
                'de' => 'Subsahara-Afrika',
                'fr' => 'Afrique subsaharienne',
                'es' => 'África subsahariana',
                'pt' => 'África Subsaariana',
            ],
            'displayOrder' => 100,
            'isActive' => true,
        ],

        // ── Oceania — sub-regions ───────────────────────────────────
        'oceania-pacific' => [
            'slug' => 'oceania-pacific',
            'shortCode' => 'OC-PA',
            'numericCode' => null,
            'parentSlug' => 'oceania',
            'name' => [
                'en' => 'Oceania & Pacific',
                'de' => 'Ozeanien & Pazifik',
                'fr' => 'Océanie & Pacifique',
                'es' => 'Oceanía y Pacífico',
            ],
            'displayOrder' => 100,
            'isActive' => true,
        ],

        // ── MENA — sub-regions ──────────────────────────────────────
        'middle-east-north-africa' => [
            'slug' => 'middle-east-north-africa',
            'shortCode' => 'ME-NA',
            'numericCode' => null,
            'parentSlug' => 'mena',
            'name' => [
                'en' => 'Middle East & North Africa',
                'de' => 'Naher Osten & Nordafrika',
                'fr' => 'Moyen-Orient & Afrique du Nord',
                'es' => 'Oriente Medio y Norte de África',
                'ar' => 'الشرق الأوسط وشمال أفريقيا',
                'tr' => 'Orta Doğu ve Kuzey Afrika',
            ],
            'displayOrder' => 100,
            'isActive' => true,
        ],
    ],
];
